/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * workerLogin.java
 *
 * Created on Jul 18, 2012, 1:44:30 PM
 */

package Workers;

import Database.Dbconnection;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author spiro16
 */
public class workerLogin extends javax.swing.JFrame {


   
    /** Creates new form workerLogin */
    public workerLogin() {
        initComponents();
      
       
      

        setSize(400, 300);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wuname = new javax.swing.JTextField();
        wpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("WORKER LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(139, 11, 78, 14);

        jLabel2.setText("USER NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(45, 62, 57, 14);

        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 57, 14);

        wuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wunameActionPerformed(evt);
            }
        });
        getContentPane().add(wuname);
        wuname.setBounds(130, 60, 120, 20);

        wpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpassActionPerformed(evt);
            }
        });
        getContentPane().add(wpass);
        wpass.setBounds(130, 100, 120, 20);

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 160, 73, 23);

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(185, 160, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wpassActionPerformed

    private void wunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wunameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String uname=wuname.getText();
        char[] pass=wpass.getPassword();
        String st=new String(pass);
       String s=JOptionPane.showInputDialog("Enter Port Number For client");
       String server=JOptionPane.showInputDialog("Enter server ip");
       String clientip = null;
        List li=new ArrayList();
        li.add(uname);
        li.add(st);
        li.add(s);
        try
        {
        InetAddress ipad =InetAddress.getLocalHost();
         clientip=ipad.getHostAddress();
         li.add(clientip);
        }
        catch(UnknownHostException unk){}
        try
        {
           so=new Socket(server,910);
          ObjectOutputStream oos=new ObjectOutputStream(so.getOutputStream());
          oos.writeObject(li);
         
           ObjectInputStream ins=new ObjectInputStream(so.getInputStream());
      String j=(String)ins.readObject();
     
     
     if(j.equals("10"))
      {
         JOptionPane.showMessageDialog(rootPane, "valid user");
         Worker obj=new Worker();
       

          this.dispose();
          obj.name(uname,s,clientip);
          
          obj.setVisible(true);
         
         
      }
            else if(j.equals("2"))
      {
           JOptionPane.showMessageDialog(rootPane, "Invalid user");
            wpass.setText("");
          wuname.setText("");
      }
             else if(j.equals("20"))
          {
                  JOptionPane.showMessageDialog(rootPane, "User Already Signin");

            }

        }
        catch(UnknownHostException unk)
        {
            unk.printStackTrace();
        }
        catch(IOException ioe)
        {
            ioe.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
            
        }

       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField wpass;
    private javax.swing.JTextField wuname;
    // End of variables declaration//GEN-END:variables
ServerSocket ss;
Socket so;


   

}
